[target.aarch64-linux-android]
ar = "/Users/louis/Desktop/bulletproof-demo/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/Users/louis/Desktop/bulletproof-demo/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/Users/louis/Desktop/bulletproof-demo/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/Users/louis/Desktop/bulletproof-demo/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/Users/louis/Desktop/bulletproof-demo/NDK/x86/bin/i686-linux-android-ar"
linker = "/Users/louis/Desktop/bulletproof-demo/NDK/x86/bin/i686-linux-android-clang"
